export const APP_LOADING_STARTED = "APP_LOADING_STARTED";
export const APP_LOADED = "APP_LOADED";

export const RECEIVE_ACCESS_TOKEN = "RECEIVE_ACCESS_TOKEN";
export const RECEIVE_AUTHED_USER = "RECEIVE_AUTHED_USER";
export const RESET_AUTHED = "RESET_AUTHED";

export const FETCHING_TWEETS = "FETCHING_TWEETS";
export const RECEIVE_TWEETS = "RECEIVE_TWEETS";
export const RECEIVE_LISTS = "RECEIVE_LISTS";
export const RECEIVE_FRIENDS = "RECEIVE_FRIENDS";
export const RECEIVE_MEMBERS = "RECEIVE_MEMBERS";

export const ADD_MEMBER = "ADD_MEMBER";
