export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RESET_AUTHED = 'RESET_AUTHED';

export const RECEIVE_TWEETS = 'RECEIVE_TWEETS';
export const RECEIVE_LISTS = 'RECEIVE_LISTS';